---
- name: provision python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
- name: copy webroot file
  hosts: all
  tasks:
    - name: copy file
      copy:
        src: files/centos7-ks.cfg
        dest: /usr/share/nginx/html/centos7-ks.cfg
