galaxy_info:
  author: Eduard Generalov <eduard@generalov.net>
  description: Move from networking to systemd-networkd (bridge will be created)
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: Debian
    versions:
    - stretch
  galaxy_tags: []
dependencies: []
