---
- name: newhost setup for debian
  become: yes
  hosts: all
  gather_facts: yes
  vars:
    usrnames:
    - ron
    - nikky
    packages:
    - build-essential
    - nmap
    - htop
    - vim
    - curl
    - net-tools
  tasks:
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{packages}}"
  - name: Create ron and nikky users
    user:
      name: "{{ item }}"
      state: present
      shell: "/bin/bash"
      groups: sudo
    loop: "{{usrnames}}"
  - name: Set authorized key for user ron
    authorized_key:
      user: ron
      state: present
      key: "{{ lookup('file', '../keys/id_rsa.pub') }}"
  - name: Set authorized key for user nikky
    authorized_key:
      user: nikky
      state: present
      key: "{{ lookup('file', '../keys/nikky.pub') }}"
  - name: passwordless sudo for sudo group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'