---
- name: Disable SWAP for docker or k8s host (1/2)
  shell: |
    swapoff -a
- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'
